import numpy as np
import pandas as pd
from ta.momentum import RSIIndicator, StochasticOscillator
from ta.volatility import BollingerBands
from ta.trend import MACD

from config import settings
from utils.logger import get_logger

logger = get_logger("features.engineer")

def create_features(df):
    """
    Computes technical indicators and creates target labels for prediction models.
    """
    logger.info("Computing features: SMAs, RSI, Daily Returns, and Volatility...")
    data = df.copy()
    
    # 1. Moving Averages
    for window in settings.SMA_WINDOWS:
        data[f'SMA_{window}'] = data['Close'].rolling(window=window).mean()
        
    # 2. RSI
    rsi_indicator = RSIIndicator(close=data['Close'], window=settings.RSI_WINDOW)
    data['RSI'] = rsi_indicator.rsi()
    
    # MACD
    macd = MACD(close=data['Close'])
    data['MACD'] = macd.macd()
    data['MACD_Signal'] = macd.macd_signal()
    
    # Stochastic Oscillator
    stoch = StochasticOscillator(high=data['High'], low=data['Low'], close=data['Close'])
    data['Stoch_K'] = stoch.stoch()
    data['Stoch_D'] = stoch.stoch_signal()
    
    # 3. Daily Returns
    data['Daily_Return'] = data['Close'].pct_change()
        
    # 4. Volatility (Standard Deviation of Daily Returns)
    data['Volatility'] = data['Daily_Return'].rolling(window=settings.VOLATILITY_WINDOW).std()

    # Drop NaNs generated by rolling windows before creating targets
    # so we don't skew sequence generation or model inputs
    data.dropna(inplace=True)
    
    # 5. Label Creation for Logistic Regression (Next Day Close > Today Close)
    # Target is calculated by shifting Next Day's close backwards
    data['Target_LR'] = (data['Close'].shift(-1) > data['Close']).astype(int)
    
    # Target for LSTM (Future absolute price / Returns)
    data['Target_Price'] = data['Close'].shift(-1)
    
    # After shifting, the last row will have NaN for targets, so drop it
    data.dropna(inplace=True)
    
    logger.info(f"Feature engineering complete. Prepared shape: {data.shape}")
    return data

def create_lstm_sequences(df, seq_length=settings.LSTM_SEQ_LENGTH):
    """
    Creates temporal sequences for LSTM training.
    """
    logger.info(f"Building LSTM sequences with window size {seq_length}...")
    
    # For LSTM, we'll use open, high, low, close, volume, and TA indicators
    feature_cols = [col for col in df.columns if col not in ['Target_LR', 'Target_Price']]
    feature_data = df[feature_cols].values
    target_data = df['Target_Price'].values
    
    X = []
    y = []
    
    for i in range(len(df) - seq_length):
        X.append(feature_data[i : i + seq_length])
        y.append(target_data[i + seq_length - 1]) # Next day's price relative to sequence end
        
    X = np.array(X)
    y = np.array(y)
    
    logger.info(f"Sequences created. X shape: {X.shape}, y shape: {y.shape}")
    
    # Return features as reference for columns later if needed
    return X, y, feature_cols
